[package]
name = "bluefire_languages"
version = "0.1.0"
authors = ["Wojciech Kluczka <wojciech.kluczka@gmail.com>"]
edition = "2018"
publish = false

[build-dependencies]
csv = "1.0"
serde = "1.0.101"
serde_derive = "1.0.101"

